-- AutoMarket Pro - DDL 0025
-- RECONSTRUIDO desde Vehicle.php; VIN cifrado corregido a VARBINARY(512).
CREATE TABLE vehicles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    owner_user_id BIGINT UNSIGNED NOT NULL,
    dealer_id BIGINT UNSIGNED NULL,
    make_id BIGINT UNSIGNED NOT NULL,
    model_id BIGINT UNSIGNED NOT NULL,
    version_id BIGINT UNSIGNED NULL,
    year SMALLINT UNSIGNED NOT NULL,
    mileage_km INT UNSIGNED NOT NULL DEFAULT 0,
    vin_encrypted VARBINARY(512) NULL,
    vin_hash CHAR(64) NULL,
    vin_snippet VARCHAR(20) NULL,
    plate_snippet VARCHAR(20) NULL,
    engine_spec VARCHAR(255) NULL,
    fuel_type_id BIGINT UNSIGNED NOT NULL,
    transmission_id BIGINT UNSIGNED NOT NULL,
    body_type_id BIGINT UNSIGNED NOT NULL,
    color_id BIGINT UNSIGNED NOT NULL,
    traction_id BIGINT UNSIGNED NULL,
    doors TINYINT UNSIGNED NULL,
    passengers TINYINT UNSIGNED NULL,
    city_id BIGINT UNSIGNED NOT NULL,
    inspection_score TINYINT UNSIGNED NULL,
    condition_status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT uq_vehicles_uuid UNIQUE (uuid),
    CONSTRAINT uq_vehicles_vin_hash UNIQUE (vin_hash),
    CONSTRAINT fk_vehicles_owner FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_dealer FOREIGN KEY (dealer_id) REFERENCES dealers (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_make FOREIGN KEY (make_id) REFERENCES vehicle_makes (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_model FOREIGN KEY (model_id) REFERENCES vehicle_models (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_version FOREIGN KEY (version_id) REFERENCES vehicle_versions (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_fuel FOREIGN KEY (fuel_type_id) REFERENCES fuel_types (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_transmission FOREIGN KEY (transmission_id) REFERENCES transmissions (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_body_type FOREIGN KEY (body_type_id) REFERENCES body_types (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_color FOREIGN KEY (color_id) REFERENCES colors (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_traction FOREIGN KEY (traction_id) REFERENCES traction_types (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_vehicles_city FOREIGN KEY (city_id) REFERENCES cities (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_vehicles_owner (owner_user_id),
    INDEX idx_vehicles_dealer (dealer_id),
    INDEX idx_vehicles_catalog (make_id, model_id, version_id),
    INDEX idx_vehicles_city (city_id),
    INDEX idx_vehicles_condition (condition_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
