CREATE TABLE payments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    uuid CHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    publication_id BIGINT UNSIGNED NULL,
    dealer_subscription_id BIGINT UNSIGNED NULL,
    concept ENUM('publicacion_aviso', 'destaque_aviso', 'suscripcion_dealer') NOT NULL,
    amount DECIMAL(14, 2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'COP',
    internal_reference VARCHAR(100) NOT NULL,
    status ENUM('pendiente', 'aprobado', 'rechazado', 'cancelado', 'reembolsado') NOT NULL DEFAULT 'pendiente',
    description VARCHAR(255) NULL,
    paid_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT uq_payments_uuid UNIQUE (uuid),
    CONSTRAINT uq_payments_internal_reference UNIQUE (internal_reference),
    CONSTRAINT fk_payments_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_payments_publication FOREIGN KEY (publication_id) REFERENCES publications (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_payments_dealer_subscription FOREIGN KEY (dealer_subscription_id) REFERENCES dealer_subscriptions (id) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX idx_payments_user_status (user_id, status),
    INDEX idx_payments_publication (publication_id),
    INDEX idx_payments_subscription (dealer_subscription_id),
    INDEX idx_payments_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
