/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Ficha detallada del vehículo. Todos los valores monetarios son COP.
 */

import React, { useState } from 'react';
import { Vehicle, LeadContactType } from '../../types/marketplace';
import { AuthStateManager } from '../../core/auth/auth.state';
import { X, ShieldCheck, Calendar, Gauge, Fuel, Settings, Car, CheckCircle2, AlertCircle, MessageSquare, Phone, Calculator, Share2, FileCheck2, Video, FileText, History, Maximize2, ChevronLeft, ChevronRight, UserCheck, Heart } from 'lucide-react';

interface VehicleDetailModalProps { vehicle: Vehicle | null; onClose: () => void; onOpenLeadModal: (vehicle: Vehicle, type: LeadContactType) => void; isFavorite?: boolean; onToggleFavorite?: (vehicle: Vehicle) => void; onRequireAuth?: (actionContext: string, pendingCallback: () => void) => void; }
const formatCop = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);

export const VehicleDetailModal: React.FC<VehicleDetailModalProps> = ({ vehicle, onClose, onOpenLeadModal, isFavorite = false, onToggleFavorite, onRequireAuth }) => {
  if (!vehicle) return null;
  const [activeImageIndex, setActiveImageIndex] = useState(0);
  const [downPaymentPercent, setDownPaymentPercent] = useState(20);
  const [loanTermMonths, setLoanTermMonths] = useState(48);
  const [activeTab, setActiveTab] = useState<'specs' | 'history' | 'documentation' | 'video'>('specs');
  const [isZoomOpen, setIsZoomOpen] = useState(false);
  const priceCop = vehicle.priceCop ?? 0;
  const downPaymentAmount = priceCop * downPaymentPercent / 100;
  const loanPrincipal = priceCop - downPaymentAmount;
  const monthlyRate = 0.089 / 12;
  const monthlyPayment = Math.round((loanPrincipal * monthlyRate) / (1 - Math.pow(1 + monthlyRate, -loanTermMonths)));

  const contact = (type: LeadContactType) => {
    const session = AuthStateManager.getInstance().getSession();
    if (!session.isAuthenticated || session.user?.role === 'visitante') { onRequireAuth?.('contactar al vendedor', () => onOpenLeadModal(vehicle, type)); return; }
    onOpenLeadModal(vehicle, type);
  };
  const favorite = () => {
    const session = AuthStateManager.getInstance().getSession();
    if (!session.isAuthenticated || session.user?.role === 'visitante') { onRequireAuth?.('guardar este vehículo en tus favoritos', () => onToggleFavorite?.(vehicle)); return; }
    onToggleFavorite?.(vehicle);
  };

  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/75 backdrop-blur-xs flex items-center justify-center p-2 sm:p-6">
    <div className="relative w-full max-w-5xl bg-white rounded-2xl shadow-2xl border overflow-hidden max-h-[94vh] flex flex-col">
      <header className="flex items-center justify-between px-6 py-3.5 border-b bg-white sticky top-0 z-20"><div className="flex items-center gap-3"><span className="text-xs font-semibold text-slate-400 uppercase">{vehicle.make} · {vehicle.model}</span><span className="text-xs text-slate-300">|</span><span className="text-xs text-slate-500 font-mono">VIN: {vehicle.vinSnippet}</span><span className="text-xs text-slate-500 font-mono">Placa: {vehicle.plateSnippet}</span></div><div className="flex gap-2"><button onClick={favorite} className="p-2 rounded-lg text-slate-500 hover:bg-slate-100"><Heart size={17} fill={isFavorite ? 'currentColor' : 'none'}/></button><button onClick={() => navigator.clipboard.writeText(window.location.href)} className="p-2 rounded-lg text-slate-500 hover:bg-slate-100"><Share2 size={17}/></button><button onClick={onClose} className="p-2 text-slate-400"><X size={20}/></button></div></header>
      <div className="overflow-y-auto p-5 sm:p-6 space-y-7">
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          <div className="lg:col-span-7 space-y-3"><div className="relative aspect-[4/3] bg-slate-950 rounded-xl overflow-hidden flex items-center justify-center"><img src={vehicle.images[activeImageIndex] || vehicle.images[0]} alt={vehicle.title} className="w-full h-full object-contain"/><span className="absolute top-3 left-3 bg-slate-900/85 text-white px-3 py-1 rounded text-xs flex items-center gap-1"><ShieldCheck size={15}/>{vehicle.inspectionScore}/100</span><button onClick={() => setIsZoomOpen(true)} className="absolute top-3 right-3 p-2 bg-slate-900/80 text-white rounded-lg"><Maximize2 size={16}/></button>{vehicle.images.length > 1 && <><button onClick={() => setActiveImageIndex(i => (i - 1 + vehicle.images.length) % vehicle.images.length)} className="absolute left-2 top-1/2 p-2 bg-black/60 text-white rounded-full"><ChevronLeft/></button><button onClick={() => setActiveImageIndex(i => (i + 1) % vehicle.images.length)} className="absolute right-2 top-1/2 p-2 bg-black/60 text-white rounded-full"><ChevronRight/></button></>}</div><div className="flex gap-2 overflow-x-auto">{vehicle.images.map((img, i) => <button key={i} onClick={() => setActiveImageIndex(i)} className={`w-20 h-14 rounded-lg overflow-hidden border-2 ${i === activeImageIndex ? 'border-amber-500' : 'border-slate-200'}`}><img src={img} alt={`Miniatura ${i + 1}`} className="w-full h-full object-cover"/></button>)}</div></div>
          <div className="lg:col-span-5 bg-slate-50 border rounded-xl p-5 space-y-5"><div><span className="text-xs text-slate-400 uppercase">{vehicle.year} · {vehicle.bodyType}</span><h2 className="font-display font-bold text-xl sm:text-2xl text-slate-900 mt-1">{vehicle.title}</h2><p className="text-xs text-slate-500 mt-1">{vehicle.city}, {vehicle.region} · {vehicle.mileageKm.toLocaleString('es-CO')} km</p></div><div className="border-t pt-3"><span className="text-xs text-slate-400 block">Precio al contado</span><div className="font-display font-bold text-3xl text-slate-900">{formatCop(priceCop)}</div><div className="text-xs font-semibold text-amber-700 mt-1"><Calculator className="inline mr-1" size={14}/>Desde {formatCop(monthlyPayment)}/mes</div></div><div className="bg-white border rounded-lg p-3"><div className="flex items-center justify-between"><span className="font-semibold text-xs flex items-center gap-1"><UserCheck size={15} className="text-emerald-600"/>{vehicle.seller.name}</span>{vehicle.seller.isVerified && <span className="text-[10px] text-emerald-700 bg-emerald-50 px-2 py-1 rounded">KYC verificado</span>}</div><p className="text-xs text-slate-500 mt-1">★ {vehicle.seller.rating} · {vehicle.seller.totalReviews} opiniones</p></div><div className="space-y-2"><button onClick={() => contact('whatsapp')} className="w-full py-2.5 bg-emerald-600 text-white font-semibold rounded-lg text-xs flex justify-center gap-2"><MessageSquare size={16}/>WhatsApp</button><div className="grid grid-cols-2 gap-2"><button onClick={() => contact('mensaje')} className="py-2.5 bg-slate-900 text-white rounded-lg text-xs">Enviar mensaje</button><button onClick={() => contact('solicitar_llamada')} className="py-2.5 bg-amber-600 text-white rounded-lg text-xs"><Phone className="inline" size={14}/> Llamada</button></div><div className="grid grid-cols-2 gap-2"><button onClick={() => contact('solicitud_informacion')} className="py-2.5 border rounded-lg text-xs">Solicitar info</button><button onClick={() => contact('test_drive')} className="py-2.5 border rounded-lg text-xs"><Calendar className="inline" size={14}/> Test Drive</button></div><button onClick={favorite} className="w-full py-2 border rounded-lg text-xs font-semibold">{isFavorite ? 'Guardado en favoritos' : 'Guardar en favoritos'}</button></div></div>
        </section>

        <section className="bg-slate-50 border rounded-xl p-5"><h3 className="font-display font-semibold text-sm uppercase mb-4">Ficha técnica</h3><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs"><div><span className="text-slate-400 block">Marca / Modelo</span><b>{vehicle.make} {vehicle.model}</b></div><div><span className="text-slate-400 block">Versión</span><b>{vehicle.version}</b></div><div><span className="text-slate-400 block">Año</span><b>{vehicle.year}</b></div><div><span className="text-slate-400 block">Kilometraje</span><b>{vehicle.mileageKm.toLocaleString('es-CO')} km</b></div><div><span className="text-slate-400 block">Motor</span><b>{vehicle.engine}</b></div><div><span className="text-slate-400 block">Potencia</span><b>{vehicle.horsepower} HP</b></div><div><span className="text-slate-400 block">Combustible</span><b>{vehicle.fuelType}</b></div><div><span className="text-slate-400 block">Transmisión</span><b>{vehicle.transmission}</b></div><div><span className="text-slate-400 block">Carrocería</span><b>{vehicle.bodyType}</b></div><div><span className="text-slate-400 block">Tracción</span><b>{vehicle.traction}</b></div><div><span className="text-slate-400 block">Puertas / pasajeros</span><b>{vehicle.doors} / {vehicle.passengers}</b></div><div><span className="text-slate-400 block">Color</span><b>{vehicle.color}</b></div></div></section>

        <section><div className="flex flex-wrap gap-2 border-b">{(['specs','history','documentation','video'] as const).map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={`px-3 py-2 text-xs font-semibold border-b-2 ${activeTab === tab ? 'border-amber-600 text-slate-900' : 'border-transparent text-slate-500'}`}>{tab === 'specs' ? `Equipamiento (${vehicle.features.length})` : tab === 'history' ? 'Historial' : tab === 'documentation' ? 'Documentación' : 'Video'}</button>)}</div>
          {activeTab === 'specs' && <div className="py-4 space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{vehicle.features.map((feature, i) => <div key={i} className="p-2.5 bg-slate-50 border rounded-lg text-xs flex gap-2"><CheckCircle2 size={15} className="text-emerald-600 shrink-0"/>{feature}</div>)}</div><p className="text-xs text-slate-600 leading-relaxed">{vehicle.description}</p></div>}
          {activeTab === 'history' && <div className="py-4 space-y-2">{(vehicle.historyLogs || []).map(log => <div key={log.id} className="p-3 border rounded-lg text-xs flex justify-between gap-3"><div><b>{log.title}</b><p className="text-slate-500">{log.description}</p></div><span className="text-slate-400 whitespace-nowrap">{log.date}<br/>{log.mileageKm.toLocaleString('es-CO')} km</span></div>)}</div>}
          {activeTab === 'documentation' && <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 py-4">{(vehicle.documentation || []).map(doc => <div key={doc.id} className="p-3 border rounded-lg text-xs"><FileCheck2 className="text-emerald-600" size={18}/><b className="block mt-2">{doc.name}</b><span className="text-slate-400">Validado {doc.verifiedAt}</span></div>)}</div>}
          {activeTab === 'video' && vehicle.videos?.[0] && <div className="py-6 text-center bg-slate-900 rounded-xl text-white"><Video className="mx-auto text-amber-500" size={36}/><p className="mt-2 font-semibold">{vehicle.videos[0].title || 'Video del vehículo'}</p><a href={vehicle.videos[0].url} target="_blank" rel="noopener noreferrer" className="inline-block mt-3 px-4 py-2 bg-amber-600 rounded-lg text-xs">Abrir video</a></div>}
        </section>

        <section className="border rounded-xl p-5"><div className="flex items-center gap-3 mb-4"><div className="w-10 h-10 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center font-bold">{vehicle.inspectionScore}</div><div><h3 className="font-semibold text-sm">Certificación Mecánica y Legal</h3><p className="text-xs text-slate-500">150 puntos evaluados</p></div></div><div className="grid sm:grid-cols-2 gap-3">{vehicle.inspectionItems.map(check => <div key={check.id} className="p-3 border rounded-lg text-xs flex gap-2">{check.status === 'passed' ? <CheckCircle2 className="text-emerald-500" size={16}/> : <AlertCircle className="text-amber-500" size={16}/>}<div><b>{check.item}</b><span className="block text-slate-500">{check.category}</span>{check.notes && <span className="text-amber-700">{check.notes}</span>}</div></div>)}</div></section>

        <section className="bg-slate-900 text-white rounded-xl p-6 space-y-5"><div className="flex items-center gap-2"><Calculator className="text-amber-400"/><h3 className="font-semibold">Simulador de financiamiento en COP</h3></div><div className="grid md:grid-cols-2 gap-6"><div className="space-y-4 text-xs"><div className="flex justify-between"><span>Cuota inicial ({downPaymentPercent}%)</span><b>{formatCop(downPaymentAmount)}</b></div><input type="range" min={10} max={50} step={5} value={downPaymentPercent} onChange={e => setDownPaymentPercent(Number(e.target.value))} className="w-full accent-amber-500"/><div className="flex justify-between"><span>Plazo</span><b>{loanTermMonths} meses</b></div><input type="range" min={12} max={72} step={12} value={loanTermMonths} onChange={e => setLoanTermMonths(Number(e.target.value))} className="w-full accent-amber-500"/></div><div className="bg-slate-800 rounded-xl p-4"><span className="text-xs text-slate-400">Cuota mensual estimada</span><div className="font-bold text-3xl text-amber-400">{formatCop(monthlyPayment)}</div><p className="text-[11px] text-slate-400 mt-1">Tasa referencial anual: 8,9%. Sujeto a evaluación financiera.</p><button onClick={() => contact('oferta')} className="w-full mt-4 py-2.5 bg-amber-600 text-white rounded-lg text-xs font-semibold">Solicitar preevaluación</button></div></div></section>
      </div>
      <footer className="px-6 py-3 bg-slate-50 border-t flex justify-between text-xs text-slate-500"><span>AutoMarket Pro · {vehicle.city}</span><button onClick={onClose} className="px-4 py-2 bg-white border rounded-lg">Cerrar ficha</button></footer>
    </div>
    {isZoomOpen && <div onClick={() => setIsZoomOpen(false)} className="fixed inset-0 z-70 bg-black/95 flex items-center justify-center p-4"><img src={vehicle.images[activeImageIndex] || vehicle.images[0]} alt="Foto ampliada" className="max-w-full max-h-full object-contain"/><button onClick={() => setIsZoomOpen(false)} className="absolute top-4 right-4 text-white"><X size={28}/></button></div>}
  </div>;
};
